### PR TITLE
Better searching for episodes

### PR DESCRIPTION
**Pull request by jerbob92**

### CODE REVIEW

**Comment by boxeehacks** [comment]
This is also already part of the other pull request...

**Comment by jerbob92** [comment]
Actually it isn't. I reverted that commit from the undertexter repository. 
https://github.com/boxeehacks/boxeehack/pull/124/files doesn't show it either.

**Comment by jerbob92** [comment]
Please do add this pull, as I said: it is reverted in the other branch, so it's not in now. Searching for TV subtitles on OpenSubtitles is a hell right now.

**Comment by boxeehacks** [comment]
hmmm it claims that my dev branch is already up to date with yours...

**Comment by boxeehacks** [comment]
does this same diff still apply?

**Comment by jerbob92** [comment]
Yeah it does, manual adding should be easy.

**Pull request closed without merging**
