### PR TITLE
Fixed replacing of homescreen feed, was broken. Also added icons back

### PR DESCRIPTION
**Pull request by jerbob92**

### CODE REVIEW

**Comment by boxeehacks** [comment]
This update breaks the message on the home screen when there is no internet connection. This is of course fine when showing recent stuff for local content, but not for the featured feed. I'll fix this to enable/disable properly...

**Comment by boxeehacks** [comment]
Cleaned this up, and nice-ified the icons to match with the rest of the UI better.

**Comment by jerbob92** [comment]
Lol, it's wrong again, "stringcompare(Skin.String(featured-feed),feed://featured/?limit=15)" should be "!stringcompare(Skin.String(featured-feed),feed://featured/?limit=15)"

**Comment by boxeehacks** [comment]
Damnit... you're too fast. I was already fixing that :)

**Comment by boxeehacks** [comment]
And some weirdness I forgot with the icons... all done now (I think :) )

**Pull request merged**
