### PR TITLE
Replace telnet with ssh, and writable /etc.

### PR DESCRIPTION
**Pull request by Neverous**
Dropbear(https://matt.ucc.asn.au/dropbear/dropbear.html) with password and pubkey support and working scp.
I could find easy way of mapping root home directory so i also made /etc writable and changed values in passwd/shadow - root password is "secret". I'm also trying to compile passwd from shadow(http://pkg-shadow.alioth.debian.org/) to allow for easy password change. 

With writable /etc its probably pointless to mount ppp config like in network.sh so i merged it into it.

### CODE REVIEW

**Comment by diff3** [comment]
I got your dropbear working, it's not working out of the box. 

1)
in /data/hack/bin
the files dbclient, dropbearkey, scp and dropbear needs to be symlink

like this "ln -s dropbear dropbearmulti"

2)
need to make root dir, because it's refered to in /etc/passwd
mkdir /data/root

3) in writable_etc.sh 

mount -o bind /data/hack-etc /etc change it to 
mount -o bind /data/hack/etc /etc

4)
you cant do a mount -o bind with only your files, so you need first copy  /etc and then add your files before mount it. 

cp -r /etc /data/hack/etc2
cd /data/hack/etc
cp -r ../etc2
cd ..
rm -r etc
mv etc2 etc
mount -o bind etc /etc

I think it's every change I made

But it's nice you got ssh working, I did't know about dropbear =)

**Comment by Neverous** [comment]
well, those changes you are talking about are made in install.sh so they should work oob (at least for me they did) ;)

**Comment by diff3** [comment]
ops, never checked install.sh =p, sorry

**Comment by diff3** [comment]
Well made a plugin out of it.

**Comment by diff3** [comment]
you don't need to compile anything, busybox got passwd =) just run busybox passwd to change password

**Comment by blentzgh** [comment]
I reached this pull looking for the dropbear plugin for boxeehacks via google.. and couldn't find it. If you guys stashed it somewhere, I sure as hell can't find it. Google is taking people looking for "ssh boxee" or "dropbear boxee" almost directly here. 

I'm not sure what else might be in the development branch, the goal for me is just to finally retrofit some ssh action on my boxeebox and then kill all the other protocols (telnet, ftp, and samba can all go).

I ended up just doing this manually by borrowing from Maciej's commits, although I care less about a writable /etc and more about a writable passwd file. Hopefully it's useful to someone else.

Once you're in via telnet, these commands should just paste right in. 

```
curl -L https://github.com/Neverous/boxeehack/blob/f968d003441df8e0c38d7870670e205832208583/hack/bin/dropbearmulti?raw=true -o /data/hack/bin/dropbearmulti
chmod +x /data/hack/bin/dropbearmulti
ln -s /data/hack/bin/dropbearmulti /data/hack/bin/dropbear
ln -s /data/hack/bin/dropbearmulti /data/hack/bin/dbclient
ln -s /data/hack/bin/dropbearmulti /data/hack/bin/ssh
ln -s /data/hack/bin/dropbearmulti /data/hack/bin/dropbearkey
ln -s /data/hack/bin/dropbearmulti /data/hack/bin/scp
ln -s /data/hack/bin/busybox /data/hack/bin/login
ln -s /data/hack/bin/busybox /data/hack/bin/passwd
mkdir -p /data/hack/etc/dropbear
/data/hack/bin/dropbearkey -t rsa -f /data/hack/etc/dropbear/dropbear_rsa_host_key
/data/hack/bin/dropbearkey -t dss -f /data/hack/etc/dropbear/dropbear_dss_host_key

cp /etc/passwd /data/hack/etc
mount -o bind /data/hack/etc /etc
/data/hack/bin/passwd
```

Enter your new root password

```
umount /etc

cat - >/data/hack/writable_passwd.sh <<EOF
mount -o bind /data/hack/etc/passwd /etc/passwd
EOF
cat - >/data/hack/dropbear.sh <<EOF
/data/hack/bin/dropbear -r /data/hack/etc/dropbear/dropbear_rsa_host_key -d /data/hack/etc/dropbear/dropbear_dss_host_key
EOF
chmod +x /data/hack/writable_passwd.sh /data/hack/dropbear.sh
/data/hack/writable_passwd.sh
/data/hack/dropbear.sh

cat - >>/data/hack/boot.sh <<EOF
sh /data/hack/writable_passwd.sh
sh /data/hack/dropbear.sh &
EOF
```

**Pull request closed without merging**
