### PR TITLE
Utorrent support

### PR DESCRIPTION
**Pull request by moiristo**
This commit adds support for Utorrent. It comes with a web interface to manage torrents.
Features:
- Upload torrents from filesystem or URL
- Auto download torrents placed in a folder
- Torrent RSS feed support (e.g. http://showrss.karmorra.info/)
- Automatic RSS feed downloads
- Place downloads in specified directory
- Specify ratio, limit bandwidth, set seed time, ...

### CODE REVIEW

**Comment by langluc** [comment]
It's possible to install ytorrent client on boxee+?

**Comment by moiristo** [comment]
The server is a kind of torrent client, which can be remotely managed by, for example, the web interface that comes with it. see http://forum.utorrent.com/viewtopic.php?id=83506

**Comment by langluc** [comment]
I dont understand. Please send me the instruction. :)

Il giorno 09/dic/2012, alle ore 20:40, Reinier de Lange notifications@github.com ha scritto:

**Comment by moiristo** [comment]
See also #94

**Comment by boxeehacks** [comment]
Going to move this into the new plugin system

**Comment by moiristo** [comment]
Great! I was already thinking that not everybody will be interested in having utorrent enabled, so there should be a way to enable and disable plugins from the settings page. Will the new plugin system support this eventually?

**Comment by diff3** [comment]
I have a 3 hour boring trainride tonight, i fix a utorrent pluggin then

Mape

26 dec 2012 kl. 10:36 skrev Reinier de Lange notifications@github.com:

**Comment by boxeehacks** [comment]
Yeah eventually I'll add a system for enabling/disabling plugins. First release though this will just be managed through FTP (just put a plugin in there and it gets run on boot, remove it and reboot and it's gone)

How'd the plugin conversion thingy go? Need any help? Everything clear in the docs (minimalist as they are a.t.m.)

**Comment by diff3** [comment]
It went well, got working utorrent, webserver and cron plugins :)

**Comment by boxeehacks** [comment]
Cool. Probably best to have a plugins repo. If you send me the files (zip?) I'll put them up on a new repo...

**Comment by diff3** [comment]
I'll send them tomorrow, got the files on my other computer and i'm on another train ride.

**Comment by boxeehacks** [comment]
Thanks. I'll close this pull request now, just send the files and I'll put them in the plugins section

**Comment by langluc** [comment]
I hav updated to ver 1.4.1 And ytorrent client disappear. :(

**Comment by diff3** [comment]
I have made a pluggin of utorrent. I link it then i got my computer nerby

1 jan 2013 kl. 15:00 skrev Luca notifications@github.com:

**Comment by diff3** [comment]
http://rapidshare.com/files/3533616893/utorrent.zip

Just unzip it in /data/plugins and reboot

**Comment by langluc** [comment]
when i go to http://192.168.0.191:1050/gui/ nothing happens

**Comment by diff3** [comment]
Rebooted?

1 jan 2013 kl. 16:43 skrev Luca notifications@github.com:

**Comment by langluc** [comment]
yes :(
Immagine

**Comment by diff3** [comment]
ok I found the error. 

http://rapidshare.com/files/689810714/utorrent.zip

or

cd /data/plugins/utorrent/bin
chmod +x *
cd ..
chmod +x webui.zip
reboot

**Comment by langluc** [comment]
Can i do the command from putty with the old utorrent folder?

Il giorno 02/gen/2013, alle ore 12:30, mape0661 notifications@github.com ha scritto:

**Comment by diff3** [comment]
Yes :)

2 jan 2013 kl. 12:37 skrev Luca notifications@github.com:

**Comment by langluc** [comment]
IT'S WORK!!!:)

**Comment by jmaferreira** [comment]
Hi guys,

I'm not sure if you've noticed this, but when using utorrent on boxee the average load (using "top") goes up to 5.5, mainly because "ld-linux.so.2" is taking over 45% of the CPU.

This makes boxee extremely slow and some services stop working (e.g. the samba server).

Watching movies is also unbearable because of the lag.

Is this just me or is it happening to you as well?

Cheers,
Miguel

**Comment by diff3** [comment]
Got to check that

Is it then your downloading or just running?

4 jan 2013 kl. 00:58 skrev jmaferreira notifications@github.com:

**Comment by jmaferreira** [comment]
Definitely when downloading. But not right after you start downloading. I'm not sure if it has something to do with the size of the file (aprox. 2GB in my case), the bandwidth use (apron. 600Kb/s) or the amount of time that the application is running (aprox. 2 hours).

I'll provide more feedback when I get enough data to replicate the lag effect.

Cheers,
Miguel

**Comment by hessius** [comment]
My downloads are stopping, under status it says: Error ??

Logger says
[20:32:20] JS error: [767] ReferenceError: Can't find variable: str
[20:32:20] JS error: [807] TypeError: 'null' is not an object (evaluating 'lang[CONST.DLG_SETTINGS_7_TRANSFERCAP_12]')

**Comment by jmaferreira** [comment]
Check your settings to see where you are storing your downloads. You should configure utorrent to save files in your external drive.

**Comment by dwall611** [comment]
When I add a torrent in the client, it shows it has started downloading and then all of a sudden i get the following error - 
"[18:57:36] JS error: [807] Uncaught TypeError: Cannot read property '262' of null"

Below is my utserver.conf and yes the external hdd is called 'boxee'.

ut_webui_port:1050
ut_webui_dir:/data/plugins/utorrent/
dir_active:/media/boxee/downloads/
dir_completed:/media/boxee/downloads/
admin_name:admin
admin_password:admin
bind_port:37455

**Comment by bwiklak** [comment]
@jmaferreira the same problem, several "ld-linux.so.2" processes, box is unusable. When stopped downloading the problem didn't stop. Should another issue be post or we should stay in this thread?

**Comment by diff3** [comment]
dwall611, looks like a webui problem, try this one https://forum.utorrent.com/viewtopic.php?id=58156

**Comment by diff3** [comment]
jmaferreira, stay in this thread. Is it still several processes then you reboot the boxee box? using telnet you can type killall utorrent to stop every process. 

Then did the problem accure? Did you start utorrent several times or during normal use?

**Comment by jmaferreira** [comment]
Hi @mape0661,

I've only started one utorrent job. There's only one "ld-linux.so.2" process taking over 40% of the CPU. The issue is hard to reproduce. I'll give it another go this weekend....

**Comment by diff3** [comment]
I'll did some testing as well

ld-linux.so.2 process taking over 5-9% of the CPU then downloading in 200kB/s 

stopped and removed torrent from gui ,did't delete the downloaded data, about 6% total
started same torrent, got about 25-34% then checking the downloaded content but then the download started again
ld-linux.so.2 was down to about 3-4% with 160kB/s download speed.

Then download speed was about 450-900 kB/s CPU usage pending between 10% and 35% so it looks like faster download are equal with more CPU usage.

I used top -p PID and watched at gui page for download speed.utorrent been running for about 1 hour total and about 5-10 min with downloads.

Then I killed the download CPU usage for ld-linux.so.2 become 0.3, but still used about 8% of mem.

I guess we can set a max download speed so BB don't get slower then necessary

I have also made a plugin of utorrent and fixed some bugs so we can use it with the plugin system that came with 1.4.0 so we don't have to reinstall it every update.

**Comment by jmaferreira** [comment]
Hi @mape0661,

Apparently if we start utorrent.sh from the command line after the boxee has booted, it works perfectly. Even with large-sized downloads and fast download rates. However, if we add utorrent.sh to the boot process by appending "sh /data/hack/utorrent.sh &" to boot.sh script it begins to show the overload use of CPU previously reported.

This is my "boot.sh" sequence:

#!/bin/sh
sh /data/hack/skin.sh &
sh /data/hack/splash.sh &
sh /data/hack/visualiser.sh &
sh /data/hack/subtitles.sh &
sh /data/hack/logo.sh &
sh /data/hack/apps.sh &
sh /data/hack/network.sh &
sh /data/hack/telnet.sh &
sh /data/hack/ftp.sh &
sh /data/hack/plugins.sh &
sh /data/hack/utorrent.sh &

This happens mostly during the data check phase that happens when we fire up utorrent.

Here's a screenshot of my top during check data:

Screen Shot 2013-01-20 at 16 21 24

However, after the checking data phase the download kicks in at 500 Mb/s and the process "mount.ntfs-3g" takes around 40% of the CPU.

Screen Shot 2013-01-20 at 16 44 05

I don't know.. It has been hard to reproduce since I've removed utorrent from the boot process. Now that I've included it again, it seems to behave abnormally again. 

Can you experience a similar behavior? I believe that if you transform utorrent.sh into a plugin you may experience the same issue.

Anyway... if I don't start it automatically it works like a charm.

Props.

**Comment by diff3** [comment]
have you a ntfs formated usb drive? 

Well anyway, try this one: https://github.com/mape0661/plugins

**Comment by jmaferreira** [comment]
Hi @mape0661,

Yes, my external drive is formatted as NTFS.

**Comment by youngchul76** [comment]
Hi mape,

This has been enquired in another post by another user but how would i go about accessing my boxee utorrent from outside my house?  I cant install the utorrent remote for windows on boxee obviously, so how would i go about accessing it from outside my home network?

Would i just type in my public ip:1050/gui or do i need open certain port on my router (i have billion bipac7800n)

**Comment by rustax** [comment]
Hey guys, I am trying to install torrent on my boxee box now, but I can't succeed. Been trying for hours, kinda newbie with the linux stuff. Is there any way you could post a thorough instruction on how to install it?

Thanks in advance,
Rustax

**Comment by dampus200** [comment]
Can anybody reupload the http://rapidshare.com/files/689810714/utorrent.zip or http://rapidshare.com/files/689810714/utorrent3.zip? I cannot get the file from the plugin to work.  If I log on by telnet and try to run plugins.sh I get this:

```
# sh plugins.sh 
plugins.sh: line 10: /data/plugins/boxeeproxy/init.sh: not found
plugins.sh: line 10: /data/plugins/cron/init.sh: not found
plugins.sh: line 10: /data/plugins/dropbear/init.sh: not found
plugins.sh: line 10: /data/plugins/ftp/init.sh: not found
plugins.sh: line 10: /data/plugins/minidlna/init.sh: not found
plugins.sh: line 10: /data/plugins/telnet/init.sh: not found
plugins.sh: line 10: /data/plugins/utorrent/init.sh: not found
plugins.sh: line 10: /data/plugins/vsftpd/init.sh: not found
plugins.sh: line 10: /data/plugins/webserver/init.sh: not found
```

And if I try to run /data/plugins/utorrent/init.sh i get this:

```
sh /data/plugins/utorrent/init.sh 
: not foundns/utorrent/init.sh: line 3: 
/data/plugins/utorrent/init.sh: line 13: syntax error: "elif" unexpected (expecting "then")
```

Thanks to anyone still reading this. Feels like this community died very quickly.

**Comment by moiristo** [comment]
You should be able to get it to work with mape's plugin repo: https://github.com/mape0661/plugins. The utorrent dir contains all the files that were in the zip.

**Comment by moiristo** [comment]
Can't test it btw, my boxeebox broke down a couple of months ago :(

**Pull request closed without merging**
