### PR TITLE
Setting to change where Boxee starts up

### PR DESCRIPTION
**Pull request by cigamit**
This adds a setting to allow the Home page to redirect to a specified page.  Currently supports Home, Movies, TV Shows, Music, Files, Apps, Pictures.

### CODE REVIEW

**Comment by cigamit** [comment]
I tried doing this in Startup.xml but got no where.  One thing I would like to add is make it so it only does it on startup, and not when you go to the Home icon on the menu.

**Comment by jerbob92** [comment]
I know there was an "autoexec.py" in the scripts folder. But I'm not sure it's being used...

**Comment by scottybgoode** [comment]
Would also like this.

**Comment by boxeehacks** [comment]
Could you please sync with the latest version on the development branch? Quite a lot has changed already and this pull request isn't compatible with the current dev version. Then do a new pull request into the development branch, so that I can better manage the release process.

So pull the current dev branch, add this in, and do a new pull request...

Thanks!

**Pull request closed without merging**
