### PR TITLE
Added a button to clear the cache

### PR DESCRIPTION
**Pull request by jerbob92**

### CODE REVIEW

**Comment by war59312** [comment]
Does this call thumbnails for TV Episodes to be recreated?

That is, for example if I manually identify a show using .nfo files today it will cause it to use the wrong thumbnail, generated from the show itself instead of the episode.

Will this cause the episode thumbnail to clear and be recreated correctly ?

**Comment by jerbob92** [comment]
I am not sure it will use the right thumbnails when you clear the cache. 
I do know it will refill the cache by itself, so best would be to just give it a try.

**Comment by war59312** [comment]
Well not ready yet to leave 1.2 firmware behind. I had nothing but nightmares with 1.5 firmware.

Will probably wait until your firmware is more stable before I give it a shot.

Was hoping you had fixed this very annoying bug (http://jira.boxee.tv/browse/BOXEE-9927). ;)

**Comment by jerbob92** [comment]
I can't view that bug. What's in it?
You have to understand that this is not a firmware. We did not manage to compile boxee for the BoxeeBox yet. 
As long as we can't compile, we won't be able to change many things because they are in boxee/xbmc core.

**Comment by war59312** [comment]
By your firmware I meant 1.5 firmware plus your hack. Sorry.

But yes I understand due to not being able to access the kernel and not being able to build from source thanks to Intel (wont give us a SDK) we are limited.

And yeah forgot the bug is marked as early-access so have to be early-access to be able to access it.

Here is a copy and past from the my original bug report from the above bug, dated 22/May/11 3:37 AM:

----Start Bug Report

The "Clear Old Thumbnails" advanced option is not clearing out the thumbnails now, even after a reboot the thumbnails are still there. 

I imagine it's because of the new caching? 
The thumbnails are not removed at all when clicking on "Clear old thumbnails". 

Not good, since now the only way to clear out cached thumbnails is to use the "clear media info from the library" advanced option in settings. :( 

also, the clear action is freezing the UI for few minutes and the user may think its is a hang.

----End Bug Report

As you can see its been broken since May 2011. ugh! :(

**Comment by jerbob92** [comment]
I'm not sure what that button was supposed to do, I will have to take a look in the source code, will do so tonight.
This might fix it, you just have to try it I guess.

**Comment by war59312** [comment]
K cool, thanks.

**Comment by boxeehacks** [comment]
Yeah this works a bit weird on Boxee. What happens is that during scraping an entry (episode, tvshow or movie) gets created in the SQLite database for each file. That entry also contains a pointer to the thumbnail that needs to be shown for that entry (poster or episode thumb).

The bug is that when you use an NFO to manually add an episode it places it in the database with a pointer to the tvshow poster instead of the episode thumbnail.

Then when it shows any thumbnail or poster or whatever the file get's loaded from wherever it is that file is, and gets cached on the boxee box.

The clear old thumbnails button removes all thumbnail caches that Boxee knows about. The patch from jerbob92 also removes caches that Boxee doesn't know about (basically the fanart caches).

However to fix the NFO issues you would need to actually modify the library SQLite database, which even after clearing the thumbnail caches will still point to the wrong file (namely the TVShow poster).

**Comment by boxeehacks** [comment]
Pulled this into the development branch.

**Comment by war59312** [comment]
Got you, which is not fixable then, yet.

Thanks for checking it out.

**Pull request closed without merging**
