### PR TITLE
webserver

### PR DESCRIPTION
**Pull request by diff3**
Webserver with php support and a Raspcontrol clone for Boxee Box

### CODE REVIEW

**Comment by jerbob92** [comment]
How much does this effect memory usage / speed?

**Comment by diff3** [comment]
Hmm i have to check what

**Comment by hessius** [comment]
Cool! Possible to make a web based boxee box manager? (To run scripts e.g. like update library remotely?)

**Comment by diff3** [comment]
With ps i got this with two people on the webpage

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
#ps aux | grep www
root      1999  0.0  0.0    952    68 ?        Ss   16:03   0:00 /data/hack/bin/busybox httpd -p 80 -h /data/hack/www -c /data/hack/httpd.conf

I'm unsure how much it will effect on cpu and ram, but i usely never turn boxee box off and i have used some sort of webserver on it from first week of hack and i have not thougt about been any slower

**Comment by diff3** [comment]
Hessius: i got https://github.com/nicholasrobinson/BoxeeBox-PHP-JSONRPC working so yes you can do complex stuff, and its running javascript, cgi-scripts and sqlite3 is already installedl

**Comment by jerbob92** [comment]
What about the PHP childs it create?
httpd stats look quite good :+1:

**Comment by diff3** [comment]
I check little later, i can use ps auxf right?

**Comment by jerbob92** [comment]
Yes

**Comment by diff3** [comment]
<pre>root      1999  0.0  0.0    952    68 ?        Ss   16:03   0:00 /data/hack/bin/busybox httpd -p 80 -h /data/hack/www -c /data/hack/httpd.conf
root      6654  0.0  0.0    960   188 ?        S    20:15   0:00  \_ /data/hack/bin/busybox httpd -p 80 -h /data/hack/www -c /data/hack/httpd.conf
root      6655  0.0  0.5  13552  3536 ?        R    20:15   0:00      \_ /data/hack/bin/php-cgi main.php
root      6668  0.0  0.0   1652   328 ?        R    20:15   0:00          \_ sh -c /data/hack/bin/busybox who -a | awk '{print $7}'
root      6669  0.0  0.0      0     0 ?        Z    20:15   0:00              \_ [busybox] <defunct>
root      6670  0.0  0.0   1516    56 ?        R    20:15   0:00              \_ awk {print $7}
</pre>

**Comment by diff3** [comment]
hard to track, had te reload the page with javascript every 0.1 s

**Comment by jerbob92** [comment]
Looks fine to me :)

**Comment by diff3** [comment]
nice =)

**Comment by gadgetchnnel** [comment]
This is great. The PHP support allows for some quite powerful stuff, such as querying the content database (which is SQLite). By doing this we could potentially create custom services, such as searching by actor or director.

**Pull request closed without merging**
