### PR TITLE
Cron, php, webserber, utorrent

### PR DESCRIPTION
**Pull request by diff3**
It's working just need some tweeking

### CODE REVIEW

**Comment by nickdima** [comment]
What's the purpose for the webserver?

**Comment by diff3** [comment]
What ever you like, i got a version of raspcontrol working on bb and i know there is a lot of php classes to access the bb from webpages

**Comment by walesmd** [comment]
I'm trying to think of a reason anyone would want a web server on their Boxee. Don't get me wrong, it's _neat_ but is there any value added? Is there a good reason to do this other than just to say, "look at this"? Does it even fall within the scope of the Boxee+ goals and/or road ahead (which, I haven't really seen clearly defined anywhere).

I could see a few potentially interesting uses for it... throw in some transcoding (can the Boxee hardware handle it?) and a nice interface, now users have the capability to watch their media library and/or use Apps from any internet connected device on the network. A quick port triggering/forwarding tutorial and those users can now do the same from anywhere in the world. But... most already have this capability through their media serving platform and/or the applications themselves.

The diagnostics page is a good idea but could be managed in a much less invasive manner, especially since the box is already running Python and most of those metrics are available via a quick `head` of a shell script.

**Comment by diff3** [comment]
Well diagnostics page was most for fun, but I want to do something fun with this 

https://github.com/nicholasrobinson/BoxeeBox-PHP-RemoteControlInterface
or
simpler https://github.com/a904guy/Boxee-Remote-Web-Version - I use this one because my remote broke down.  and it's working great to have it on the boxee

But it's no need to start the webserver if you don't want to =)

I use the last one, because my remote broke down

**Comment by nickdima** [comment]
There's no practical use of those scripts sitting on the Boxee Box. The scripts are just wrappers for Boxee's HTTP API, it makes sense for them to sit on some other machine that needs to control Boxee.

**Pull request closed without merging**
