### PR TITLE
Music icon visibility setting

### PR DESCRIPTION
**Pull request by hessius**
Added a setting to show / hide music icon
(as per a comment on issue #105)

### CODE REVIEW

**Comment by scottybgoode** [comment]
Awesome!  I just posted about this actually. Would it also be possible for a WEB icon visibility setting?

**Comment by hessius** [comment]
Yeah sure, I was going to add ones for the watch later and friends (which I don't use) might as well throw in browser.
Don't know if centering is going to work properly though if you hide more than one icon, we'll see!

**Comment by hessius** [comment]
I have now added visibility settings for music, watch later, friends, browser. (thus addressing #126)
Centering works fine.
Will do a pull tomorrow after I add some small adjustments to it.

**Comment by boxeehacks** [comment]
Will pull this into development first, so we can better manage releases, and do cleanup stuff as well before it goes live to users...

**Comment by boxeehacks** [comment]
(pulled it into dev)

Btw... is this also already tested with the LiveTV functionality? I think (just looking at the XMLs) that those animation position settings might conflict between the two...

**Comment by hessius** [comment]
This was my first pull request ever - Will pull to dev in the future ;)

Haven't checked it with LiveTV, didn't think of it... It shouldn't be more trouble than remove the dvb connected condition?
I will make a new pull of this in a few hours with more options, will test before that!

**Pull request closed without merging**
