### PR TITLE
Added icon alternatives to main window and browse menu

### PR DESCRIPTION
**Pull request by D34dmeat**
made it possible to select wich icons you want on the main menu and browse menu and started a 
little dropdown menu project on the main menu.

### CODE REVIEW

**Comment by d4yz** [comment]
what exactly is this? seems like you added navix remix

**Comment by D34dmeat** [comment]
Yes its several different submits, one is navi-x-remix and the others are the option to add more icons to the main menu or have them circle as a ugly dropdown

**Comment by D34dmeat** [comment]
The navi-x-remix is just because. I added an icon for it on the menus

**Comment by D34dmeat** [comment]
The menu icon changes only apply to the files main.xml boxeehack_settings.py, custom_boxeehack.xml and boxee_browse_menu.xml and there probably is some stray code that shouldent be there coming from the old utorrent menu but i don't know how to remove unwanted code from github, it keeps sticking it in there

**Comment by D34dmeat** [comment]
Sorry i meant to say home.xml not main.xml

**Comment by D34dmeat** [comment]
Try ftp:ing the named files from my fork into your boxee and you'll have the option to add all icons at the same time if you want

**Comment by boxeehacks** [comment]
Pull requests should always be made by taking the latest dev branch, patching in only the changes that are needed (this is waaay too much) and doing a pull request on the "development" branch, and not the master. That way ensures that the changes are easy to incorporate (this one cannot be automatically merged for instance) and that it gets tested first before going to end-users (by pulling it into dev first).

**Pull request closed without merging**
