### PR TITLE
VPN Shortcut added to the Boxee Browse Menu

### PR DESCRIPTION
**Pull request by dmike3**
This allows you to connect to your VPN connection from the main pop-up window instead of going through the settings/network/vpn/connect.

### CODE REVIEW

**Comment by dmike3** [comment]
How does the merge process work?

**Comment by recursivemonk** [comment]
mike3y, it looks like the new fix for the MTU VPN issue will have an effect on your changes.  I am running your VPN button shortcut in conjunction with my VPN MTU modifications and it seems that the shortcut circumvents my MTU hack/fix.  Not sure if we adjust my hack to accommodate yours, or vice-versa.  

You can read what I'm trying to do here:
https://github.com/boxeehacks/boxeehack/issues/87

**Comment by boxeehacks** [comment]
Also still not sure about what the use-case of this is. I don't use a VPN myself, so I definitely wouldn't want to see this button on my screen whenever I open that menu. So at the very least the button should be set visible or not from a settings menu...

Didn't really get an answer when I asked this before, but why not just leave the VPN enabled? Still don't get why you'd want to access this so often... sounds like a setting that belongs in the settings menu...

**Comment by boxeehacks** [comment]
Also any pull requests should go to the development branch first by the way, but we can worry about that later...

Also sorry, not trying to be difficult or anything ;) ... just want to make sure that the stuff that goes in actually is helpful to people, and to do so I also need to understand why its needed or wanted :)

**Comment by recursivemonk** [comment]
for all users outside of the USA the VPN is important and often enabled/disabled frequently.  Here's my scenario just to give an example:

I live outside the USA and I watch lots of MLB.tv using the boxee app.  The performance of MLB.tv is terrible via my VPN account when compared to using my regular internet connection.

However, I listen to Pandora alot and have a Netflix account I use frequently.  In order get Pandora and Netflix working, I have to enable the VPN, but that is the only time I want to use it.  So frequent VPN access is pretty handy for me.

That being said, the VPN shortcut button on the main browser dialog is a  nice convenience, but is really not that necessary.  It isn't that hard to enable the VPN via the current Boxee interface.

The VPN MTU tweak (Issue https://github.com/boxeehacks/boxeehack/issues/87), however, is pretty _critical_.  If I do not adjust the MTU, the VPN connection breaks as soon as I launch Netflix. The importance and issues surrounding the VPN MTU in PPPOE is documented on Jira so I won't go into full details on it here.

**Comment by dmike3** [comment]
Exactly what winedog mentioned. It's basically the option of not having to dig through your menus. What I can do is add the ability to turn on or off the shortcut. 

This just makes my life and I'm sure others a lot easier to switch between VPN and not VPN.

**Comment by dmike3** [comment]
I add a MTU fix that should work. Please report back and let me know.

**Comment by recursivemonk** [comment]
I've just done some testing on this. The modification doesn't work unless you sleep the script for longer.  On my box it only touched the MTU on eth0 successfully.  I changed sleep to 4 and it changed the MTU on ppp0 about 9/10 times. On one occasion it didn't work, but I was unable to repeat that.  Changing to sleep 5 would probably be even more consistent for the MTU successfully getting applied to ppp0....perhaps in situations when the VPN handshake between Boxee and the VPN server are a tad slow.

Once I went to sleep 4, everything seemed to work pretty good and be pretty stable.

So I decided to stress test your shortcut.  Unfortunately, I have uncovered a few minor bugs.  

It seems that in some situations if you try and initiate the VPN via your shortcut, but then you disconnect it via the Boxee Network dialog, it can cause the VPN to fail and send the Boxee into a state where it thinks the network is crashed and it goes offline. It may be possible that Disconnect from the Network dialog also becomes 'greyed out'. Toggling your VPN shortcut may restore it, but then it usually causes the UI to crash and restart.

Also, another anomaly is that depending on the order with which you toggle the VPN via the Boxee Network dialog and your VPN shortcut, the MTU of ppp0 can vary between 1400 and 1396.  That difference of 1396 is for 4 packets of overhead allowed for an encrypted VPN tunnel. 

Both of these bugs seems to originate from using  a mixture of the VPN shortcut and Boxee's Network VPN dialog.

I could not make the bugs 100% reproduceable with a specific sequence.  Sometimes they came up, sometimes they didn't.  

The most consistent way that I found to reproduce the bug was to do the following from a cold boot-up (but even this wasn't 100% reproduceable):

1) Initiate VPN from shortcut
2) Disconnect VPN from the standard Boxee VPN menu
3) Boxee might think it is offline
4) Toggle VPN shortcut
5) Boxee appears to come online followed by a crash/restart of the Boxee UI

Now.....for those of us using your shortcut for the VPN, it seems unlikely that they would use a mixture of the shortcut and the Boxee Network dialog.  The performance of your shortcut seemed pretty stable as long as I didn't muck around with using the Boxee Network dialog.   I only did this for beta testing/stress testing reasons and thought I should inform you.

**Comment by boxeehacks** [comment]
Ah ok makes sense (referring to the why of the switching of VPNs). I'm outside the US as well, but am using unblock-us.com and that only redirects specific traffic through special servers, which in my experience works a lot better than most VPNs. E.g. Netflix hosts their content on a CDN (content delivery network) that isn't geo-locked. But getting at a file only requires the geo-circumvention. So not using a VPN, but a DNS based redirect service is much much faster in usage since it only redirects the handshake and everything else goes at full speed.

Another benefit is that they redirect traffic through a specific country based on the service you're accessing. So I can on the same connection view local content (Dutch), netflix (US) and BBC iPlayer (UK).

That said, if you ARE dependent on a VPN, and have such differing results when either connected or not connected, then this makes sense.

---

We should add a toggle to add or remove this from the menu through the settings though. I wouldn't want non-vpn users to get a logo that doesn't make sense to them added in their menu.

As far as the sleep timeout is concerned... would it maybe be an idea to set the MTU immediately, then again after 2 seconds, then again after 3 more (5) and a final time after 5 more (10). That way it should have the right MTU as fast as possible, but even if it fails because it's too soon, then it'll still be applied at some point...

**Comment by recursivemonk** [comment]
DNS solutions like unblock-us or smartdns are great, but if your ISP uses a transparent proxy (like several of the major ISPs in NZ), unblock-us doesn't work. Your only solution is to use a VPN.  I hadn't fully tested unblock-us though...I thought all the data traveled through a proxy, not just the handshake.

**Comment by boxeehacks** [comment]
Something like unblock-us works with a transparent proxy just as well. It's just sending and receiving data from a different IP address for some hostnames (such as netflix.com). On that different IP address there is then a proxy which handles that specific service. Even a transparent proxy will only proxy the data to that IP address, so will work just as nicely.

But there are legitimate reasons still to use a VPN... Something like unblock-us has to specifically implement support for a service to work, because all other traffic just takes the normal route. So that means only a specific set of services is supported (e.g. Hulu, Netflix) but not others (e.g. OnLive notably doesn't work).

**Comment by recursivemonk** [comment]
I know this is a little off-topic, but I can tell you that 100% for sure transparent proxies can break the unblock-us service.  I have tested unblock-us with three different major ISPs here in New Zealand and using unblock-us I was not able to access Hulu, Netflix or BBC.

**Comment by dmike3** [comment]
I will give the ability to turn off and on the option of enabling this shortcut.

**Comment by dmike3** [comment]
Looks like I"ll have to do a re-pull again. I'll do this with the development branch once I get it fixed up here. I noticed the new VPN fix /etc/ppp has broken something with my scripts.

**Comment by recursivemonk** [comment]
the new VPN fix broke VPN across the board :(

**Comment by boxeehacks** [comment]
I know... I put in a fix just now (1.3.2) that should work properly

**Pull request merged**
