### PR TITLE
View Fanart in TV Overview and Episode View

### PR DESCRIPTION
**Pull request by d4yz**
Before it would only show fanart for TV shows on the Overview screen. Now you will see fanart on the episode view as well

### CODE REVIEW

**Comment by d4yz** [comment]
not sure why i got all the other commits but only hack/boxee/skin/boxee/720p/boxee_browse_views.xml is needed and is correct

**Comment by d4yz** [comment]
okay i made more changes to boxee_browse_views.xml.

-When you highlight a tv episode it is semi transparent so that it doesnt block the fanart completly
-When viewing TV Episodes and scrolling down, the TV episodes would be too high and block the TV Show name. Cleaned that up.

**Comment by boxeehacks** [comment]
I also did a complete rewrite of how fanart is gathered, so had to refactor this quite a bit. This is now in the 1.4.0 dev branch...

**Comment by d4yz** [comment]
solitude, i downloaded the dev brank and it doesnt seem to load my fanart in the episode view. i do see that it tries to because the background is darker and you can see that overlay however the fanart.jpg is not loaded.

**Comment by boxeehacks** [comment]
Yeah that is because of another sideways related thing I'm still working on. Is as expected :)

**Comment by ghost** [comment]
I think is cool what you people do with the boxee box but don't put to much shit in the boxee it wil make it only slower and more bugs wil come thanks for the work :) 
maybe we can expend the internal mem ??

**Comment by ghost** [comment]
overclock the boxee lol !

**Pull request closed without merging**
