### PR TITLE
We need replacewindow, it makes the current view reload

### PR DESCRIPTION
**Pull request by jerbob92**

### CODE REVIEW

**Comment by boxeehacks** [comment]
There is already a replacewindow further up that does this. The commented out one was just part of a piece of test-code to try and force a reload of the library.

**Comment by jerbob92** [comment]
Weird, I didn't see it. + My window wasn't reloading.

**Comment by boxeehacks** [comment]
Well at least sometimes it updates so fast I don't see it either, but it does happen. It just sometimes doesn't update the flags until later when the boxee executable requests those listitems again. Couldn't yet find a way to force that retrigger unfortunately...

**Comment by jerbob92** [comment]
For me, replacewindow worked every time. But that was after the stacking of queries. Maybe we need add a wait for sqlite3 to write away changes. It might be db is still locked when we do a replacewindow.

**Comment by boxeehacks** [comment]
Yeah what seems to happen is that if the request takes long enough then it will trigger a reload properly. However it really is the amount of time the DB is used or something like that, because just waiting (pretty much any delay I tried) after the DB stuff and then doing the replacewindow would work just as inconsistently. However when I do a large show with multiple seasons, it pretty much always works like it should. Somehow if the dbase stuff happens too fast...

Will try some more things tonight. Have some ideas I can try; e.g. delaying for a while, and then doing a final update on the DB, or something like that...

**Comment by jerbob92** [comment]
I just had this idea last night:
AFAIK, os.system is blocking. Why don't we just do another dummy query after the insert/delete query?
Like ".timeout 100000;\nSELECT \* FROM idWatched;\n"

The .timeout will wait for the db to be unlocked, so after that "dummy" query, we should be able to do a replacewindow.

**Comment by boxeehacks** [comment]
Can't test until later tonight, but definitely worth a shot. Could even do an insert of random data followed by a delete to try and force an update maybe? Some new things to test :)

**Comment by jerbob92** [comment]
I wouldn't do another insert/delete as this _might_ cause another lock.
".timeout 100000;\nSELECT \* FROM idWatched;\n"
That should be enough to know when the lock has been removed.

**Pull request closed without merging**
